sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 3306
    database: sky_take_out
    username: root
    password: 123

  #TODO
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
